subdir = src/backend/access/bwtree
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	bwtree.o \
	bwtreeconsolidate.o \
	bwtreedelta.o \
	bwtreeepoch.o \
	bwtreeinsert.o \
	bwtreemap.o \
	bwtreepage.o \
	bwtreescan.o \
	bwtreesearch.o \
	bwtreesmo.o \
	bwtreesort.o \
	bwtreeutils.o \
	bwtreevalidate.o

include $(top_srcdir)/src/backend/common.mk
